---

- name: Install base packages
  become: yes
  become_user: root
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - build-essential
    - tree
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - htop
  tags: packages
