# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160629_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Article')),
            ],
            bases=('articles.article',),
        ),
    ]
