# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_videoarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoarticle',
            name='subtitles',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='videoarticle',
            name='video_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
