# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_servicearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 12, 40, 9, 762755, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 12, 40, 17, 222506, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
