---

virtualenv_path: /home/fadawar/venv
application_path_server: /home/fadawar/application/
application_path_latest: "{{ application_path_server }}latest/"
application_path_latest_file: "{{ application_path_server }}latest" # The can not be '/' at the end when creating symbolic link

# Nginx
nginx_log_path: /home/fadawar/logs
nginx_static_dir_path: "{{ application_path_latest }}static/"

# Gunicorn
gunicorn_user: fadawar
gunicorn_group: fadawar
gunicorn_num_workers: 3
gunicorn_max_requests: 0

# PostgreSQL
db_name: "{{ application_name }}_db"
db_user: "{{ application_name }}"
db_password: nE3PcX9eCdh9NZDQUdTs

# Django
django_static_path: "{{ nginx_static_dir_path }}"
django_debug: "False"
django_allowed_hosts: "['ubuntu-test-nok3aolb.cloudapp.net', '.spinehero.com', '13.69.255.1']"

# SSL
enable_ssl: yes