---

virtualenv_path: /home/vagrant/venv
application_path_server: /home/vagrant/application/
application_path_latest: "{{ application_path_server }}latest/"
application_path_latest_file: "{{ application_path_server }}latest" # The can not be '/' at the end when creating symbolic link

# Nginx
nginx_log_path: /vagrant/logs
nginx_static_dir_path: "{{ application_path_latest }}static/"

# Gunicorn
gunicorn_user: vagrant
gunicorn_group: vagrant
gunicorn_num_workers: 3
gunicorn_max_requests: 0

# PostgreSQL
db_name: "{{ application_name }}_db"
db_user: "{{ application_name }}"
db_password: "{{ vault_db_password }}"

# Django
django_static_path: "{{ nginx_static_dir_path }}"
django_debug: "True"
django_allowed_hosts: "['*', ]"
django_secret_key: "{{ vault_django_secret_key }}"

# SSL
enable_ssl: no