---

virtualenv_path: /app/venv
application_path_server: /application/
application_path_latest: "{{ application_path_server }}latest/"
application_path_latest_file: "{{ application_path_server }}latest" # There can not be '/' at the end when creating symbolic link

# Nginx
nginx_log_path: /app/logs
nginx_static_dir_path: "{{ application_path_latest }}static/"
nginx_media_dir_path: "{{ application_path_server }}media/"

# Gunicorn
gunicorn_user: root
gunicorn_group: root
gunicorn_num_workers: 5
gunicorn_max_requests: 0

# PostgreSQL
db_name: "{{ application_name }}_db"
db_user: "{{ application_name }}"
db_password: "{{ vault_db_password }}"

# Django
django_static_path: "{{ nginx_static_dir_path }}"
django_media_root_path: "{{ nginx_media_dir_path }}"
django_debug: "False"
django_allowed_hosts: "['spolocenstvosiloe.sk', '185.122.56.160']"
django_secret_key: "{{ vault_django_secret_key }}"
django_email_host_user: "{{ vault_django_email_host_user }}"
django_email_host_pass: "{{ vault_django_email_host_pass }}"

# SSL
enable_ssl: no